import type { District, Category } from './types';

export const districts: District[] = [
  { id: 1, name: 'Angul' },
  { id: 2, name: 'Balangir' },
  { id: 3, name: 'Balasore' },
  { id: 4, name: 'Bargarh' },
  { id: 5, name: 'Bhadrak' },
  { id: 6, name: 'Boudh' },
  { id: 7, name: 'Cuttack' },
  { id: 8, name: 'Deogarh' },
  { id: 9, name: 'Dhenkanal' },
  { id: 10, name: 'Gajapati' },
  { id: 11, name: 'Ganjam' },
  { id: 12, name: 'Jagatsinghpur' },
  { id: 13, name: 'Jajpur' },
  { id: 14, name: 'Jharsuguda' },
  { id: 15, name: 'Kalahandi' },
  { id: 16, name: 'Kandhamal' },
  { id: 17, name: 'Kendrapara' },
  { id: 18, name: 'Keonjhar' },
  { id: 19, name: 'Khordha' },
  { id: 20, name: 'Koraput' },
  { id: 21, name: 'Malkangiri' },
  { id: 22, name: 'Mayurbhanj' },
  { id: 23, name: 'Nabarangpur' },
  { id: 24, name: 'Nayagarh' },
  { id: 25, name: 'Nuapada' },
  { id: 26, name: 'Puri' },
  { id: 27, name: 'Rayagada' },
  { id: 28, name: 'Sambalpur' },
  { id: 29, name: 'Subarnapur' },
  { id: 30, name: 'Sundargarh' },
];

export const categoryLabels: Record<Category, string> = {
  'NBW': 'NBW Execution',
  'Conviction': 'Conviction',
  'Narcotics': 'Narcotic Seizures',
  'Missing Person': 'Missing Persons Traced',
  'Firearms': 'Firearms Seized',
  'Sand Mining': 'Illegal Sand Mining Cases',
  'Preventive Actions': 'Preventive Actions',
  'Important Detections': 'Important Detections',
  'Property Crime Cases': 'Property Crime Cases',
  'Crime Against Women': 'Crime Against Women',
  'Cybercrime': 'Cybercrime',
  'Others': 'Others',
};
